ccflags-y += -I../vendor/lenovo/camera/camera-driver
ccflags-y += -I../vendor/lenovo/camera/camera-driver/sensor/io
ccflags-y += -I../vendor/lenovo/camera/camera-driver/sensor/cci
obj-$(CONFIG_LENOVOB_CAMERA) += msm_ois.o
