ccflags-y += -Idrivers/media/platform/msm/camera-driver/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera-driver
ccflags-y += -Idrivers/media/platform/msm/camera-driver/sensor/io
obj-$(CONFIG_LENOVOB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_LENOVOB_CAMERA) += msm_led_trigger.o
obj-$(CONFIG_LENOVOB_CAMERA) += msm_led_i2c_trigger.o
obj-$(CONFIG_LENOVOB_CAMERA) += msm_led_torch.o
obj-$(CONFIG_LENOVOB_CAMERA) += msm_flash.o
