ccflags-y += -I../vendor/lenovo/camera/camera-driver
ccflags-y += -I../vendor/lenovo/camera/camera-driver/isp/
ccflags-y += -I../vendor/lenovo/camera/camera-driver/sensor/io
obj-$(CONFIG_LENOVO_CPP) += msm_cpp.o
