ccflags-y += -Idrivers/media/platform/msm/camera-driver
ccflags-y += -Idrivers/media/platform/msm/camera-driver/isp/
ccflags-y += -Idrivers/media/platform/msm/camera-driver/sensor/io
obj-$(CONFIG_LENOVO_CPP) += msm_cpp.o
